scan_timeout = 60
add_newline = false
command_timeout = 1000

[line_break]
disabled = true

[directory]
read_only = " ğŸ”’"
style = "bold yellow"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "ï€"
not_executable_symbol = "ï‘®"
sigint_symbol = "ï­¦"
map_symbol = true

[git_branch]
format = "[${symbol}${branch}]($style) "

[package]
format = "[${symbol}(${version} )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = "[${symbol}(${version} )]($style)"

[php]
format = "[${symbol}(${version} )]($style)"

[java]
format = "[${symbol}(${version} )]($style)"

[rust]
format = "[${symbol}(${version} )]($style)"

[golang]
format = "[${symbol}(${version} )]($style)"

[lua]
format = "[${symbol}(${version} )]($style)"

[docker_context]
format = "[${symbol}(${version} )]($style)"

[c]
format = "[${symbol}(${version} )]($style)"
symbol = "î˜ "

[ruby]
format = "[${symbol}(${version} )]($style)"
symbol = "î‘ "
